export const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

export const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';
export const BOOK_REMOVED_FROM_CART = 'BOOK_REMOVED_FROM_CART';
export const ALL_BOOKS_REMOVED_FROM_CART = 'ALL_BOOKS_REMOVED_FROM_CART';

export const ADD_BOOK_TO_BASKET = 'ADD_BOOK_TO_BASKET';
export const REMOVE_BOOK_FROM_BASKET = 'REMOVE_BOOK_FROM_BASKET';
export const CLEAN_BASKET = 'CLEAN_BASKET';